apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1m
      evaluation_interval: 30s

    scrape_configs:
      - job_name: "reco-app"

        static_configs:
          - targets: ["reco-service.monitoring.svc.cluster.local:8000"]
